### ISSUE TITLE
Incorrect times calculated when system timezone does not match bot's configured timezone

### ISSUE THREAD

**Issue by AdmiralNemo** [anoadragon453/matrix-reminder-bot#36] opened 2020-07-15 15:04 UTC
I can't seem to get the bot to remind me at the correct time.  It seems confused by time zones:

> **Dustin C. Hatch**
> !remindme in 5 minutes; test
> **reminders**
> Error: The given time 'in 5 minutes' is in the past.

> **Dustin C. Hatch**
> !remindme in 5 minutes CDT; test
> **reminders**
> An unknown error occurred: can't compare offset-naive and offset-aware datetimes

If I set an absolute time, it still doesn't work:

> **Dustin C. Hatch**
> !remindme 14:55; test
> **reminders**
> OK, I will remind you on Jul 15 2020, 14:55!

14:55 came and went with no reminder, so I tried using the bot's time zone instead of my client's:

> **Dustin C. Hatch**
> !remindme 9:58; test 2
> **reminders**
> OK, I will remind you on Jul 16 2020, 09:58!

How is this supposed to work?

**Comment by anoadragon453** [comment] 2020-07-16 01:56
Do you have an appropriate time zone set in your config file? By default the bot will operate on UTC unless otherwise specified.

**Comment by AdmiralNemo** [comment] 2020-07-16 12:50
Yes, I meant to say that the bot's time zone is set to America/Chicago (CDT), but my client was using UTC (Riot on Firefox w/ privacy.resistFingerprinting enabled).

Regardless of the setting, shouldn't I be able to provide a specific time zone in my commands?

**Comment by AdmiralNemo** [comment] 2020-07-16 15:27
Ok...then how am I supposed to set reminders?  It cannot handle relative time zones (i.e. "in 5 minutes" is "in the past"), and setting an absolute time is ambiguous (does it use the client's time zone or the bots?).

**Comment by anoadragon453** [comment] 2020-07-16 20:44
Hmm, "in 5 minutes" should work. The timezone "America/Chicago" wouldn't happen to be different from the system time of the box the bot is running on, is it?

**Comment by anoadragon453** [comment] 2020-07-16 20:52
Hm, ok after switching my box and bot to a timezone that's behind UTC I'm facing this problem as well.

**Comment by anoadragon453** [comment] 2020-07-16 21:17
OK, I've pushed a potential fix in https://github.com/anoadragon453/matrix-reminder-bot/commit/ee856ef8f14ecd479ea45658a1d78513e199e663. Could you try that (or the latest docker tag once the containers [finish building](https://hub.docker.com/r/anoa/matrix-reminder-bot/tags)) and see if it solves your relative reminder issue?

**Comment by AdmiralNemo** [comment] 2020-07-16 21:17
Yeah, I was thinking about that earlier.  The system timezone is UTC on the machine running the bot.  That does explain why it is confused by both relative and absolute times.

**Comment by anoadragon453** [comment] 2020-08-28 10:48
I've made further timezone fixes in https://github.com/anoadragon453/matrix-reminder-bot/commit/b7be83d6a9c2f132ea2abee5e5d8be63d48ec595.

The issue for relative timezones not working is a duplicate of https://github.com/anoadragon453/matrix-reminder-bot/issues/33

If you're still having timezone troubles, please open a new issue. :crossed_fingers: they're mostly fixed now.

**Closed by anoadragon453** 2020-08-28 10:48 UTC
