### ISSUE TITLE
alarm deltas are broken

### ISSUE THREAD

**Issue by HarHarLinks** [anoadragon453/matrix-reminder-bot#42] opened 2020-08-15 12:52 UTC
This is running the `latest` docker container as of 2020-08-15 12:10 UTC.

Implicit deltas seem to be `None` and do not correctly inserted as the default delta into the db.
Explicit deltas work as expected, except the alarm message prints the default delta instead of the actual delta.

```
matrix-reminder-bot    | 2020-08-15 12:11:46,985 | matrix_reminder_bot.callbacks [DEBUG] Command received: !alarmme 14:15; test alarms
matrix-reminder-bot    | 2020-08-15 12:11:46,986 | matrix_reminder_bot.bot_commands [DEBUG] Parsing command arguments: 14:15; test alarms
matrix-reminder-bot    | 2020-08-15 12:11:46,986 | matrix_reminder_bot.bot_commands [DEBUG] Got time: 14:15
matrix-reminder-bot    | 2020-08-15 12:11:47,037 | matrix_reminder_bot.bot_commands [DEBUG] Creating reminder in room !mybotroom:myhomeserver.tld with delta None: test alarms
matrix-reminder-bot    | 2020-08-15 12:11:47,038 | apscheduler.scheduler [INFO] Added job "Reminder._fire" to job store "default"
matrix-reminder-bot    | 2020-08-15 12:11:47,043 | apscheduler.scheduler [DEBUG] Looking for jobs to run
matrix-reminder-bot    | 2020-08-15 12:11:47,043 | apscheduler.scheduler [DEBUG] Next wakeup is due at 2020-08-15 14:15:00+02:00 (in 192.956408 seconds)
matrix-reminder-bot    | 2020-08-15 12:15:00,005 | apscheduler.scheduler [DEBUG] Looking for jobs to run
matrix-reminder-bot    | 2020-08-15 12:15:00,005 | apscheduler.scheduler [INFO] Removed job 8a6738e8b5f14422bd683404965e92fe
matrix-reminder-bot    | 2020-08-15 12:15:00,005 | apscheduler.scheduler [DEBUG] Next wakeup is due at 2020-08-19 11:07:00+02:00 (in 334319.994624 seconds)
matrix-reminder-bot    | 2020-08-15 12:15:00,006 | apscheduler.executors.default [INFO] Running job "Reminder._fire (trigger: date[2020-08-15 14:15:00 CEST], next run at: 2020-08-15 14:15:00 CEST)" (scheduled at 2020-08-15 14:15:00+02:00)
matrix-reminder-bot    | 2020-08-15 12:15:00,006 | matrix_reminder_bot.reminder [DEBUG] Reminder in room !mybotroom:myhomeserver.tld fired: test alarms
matrix-reminder-bot    | 2020-08-15 12:15:00,007 | apscheduler.scheduler [INFO] Added job "Reminder._fire_alarm" to job store "default"
matrix-reminder-bot    | 2020-08-15 12:15:00,009 | apscheduler.scheduler [DEBUG] Looking for jobs to run
matrix-reminder-bot    | 2020-08-15 12:15:00,009 | apscheduler.scheduler [DEBUG] Next wakeup is due at 2020-08-15 14:20:00.006599+02:00 (in 299.996922 seconds)
matrix-reminder-bot    | 2020-08-15 12:15:00,310 | matrix_reminder_bot.reminder [DEBUG] Cancelling reminder in room !mybotroom:myhomeserver.tld: test alarms
matrix-reminder-bot    | 2020-08-15 12:15:00,314 | apscheduler.scheduler [INFO] Removed job 191e84a4c91e45558219048be6df83ed
matrix-reminder-bot    | 2020-08-15 12:15:00,315 | apscheduler.executors.default [INFO] Job "Reminder._fire (trigger: date[2020-08-15 14:15:00 CEST], next run at: 2020-08-15 14:15:00 CEST)" executed successfully
matrix-reminder-bot    | 2020-08-15 12:20:00,029 | apscheduler.scheduler [DEBUG] Looking for jobs to run
matrix-reminder-bot    | 2020-08-15 12:20:00,029 | apscheduler.scheduler [DEBUG] Next wakeup is due at 2020-08-19 11:07:00+02:00 (in 334019.970574 seconds)
```
At this point, the alarm should "ring" with 5m default delta, but it is not found and at this point completely gone. So I start testing with explicitly given interval:
```
matrix-reminder-bot    | 2020-08-15 12:21:26,493 | matrix_reminder_bot.callbacks [DEBUG] Command received: !alarmme every 1m; 1m; test explicit alarms
matrix-reminder-bot    | 2020-08-15 12:21:26,493 | matrix_reminder_bot.bot_commands [DEBUG] Parsing command arguments: every 1m; 1m; test explicit alarms
matrix-reminder-bot    | 2020-08-15 12:21:26,493 | matrix_reminder_bot.bot_commands [DEBUG] Got time: every 1m
matrix-reminder-bot    | 2020-08-15 12:21:26,493 | matrix_reminder_bot.bot_commands [DEBUG] Got recurring time: 1m
matrix-reminder-bot    | 2020-08-15 12:21:26,508 | matrix_reminder_bot.bot_commands [DEBUG] Recurring timedelta: 0:01:00
matrix-reminder-bot    | 2020-08-15 12:21:26,508 | matrix_reminder_bot.bot_commands [DEBUG] Start time: 1m
matrix-reminder-bot    | 2020-08-15 12:21:26,519 | matrix_reminder_bot.bot_commands [DEBUG] Creating reminder in room !mybotroom:myhomeserver.tld with delta 0:01:00: test explicit alarms
matrix-reminder-bot    | 2020-08-15 12:21:26,519 | apscheduler.scheduler [INFO] Added job "Reminder._fire" to job store "default"
matrix-reminder-bot    | 2020-08-15 12:21:26,523 | apscheduler.scheduler [DEBUG] Looking for jobs to run
matrix-reminder-bot    | 2020-08-15 12:21:26,524 | apscheduler.scheduler [DEBUG] Next wakeup is due at 2020-08-15 14:22:26+02:00 (in 59.475941 seconds)
matrix-reminder-bot    | 2020-08-15 12:22:26,029 | apscheduler.scheduler [DEBUG] Looking for jobs to run
matrix-reminder-bot    | 2020-08-15 12:22:26,029 | apscheduler.scheduler [DEBUG] Next wakeup is due at 2020-08-15 14:23:26+02:00 (in 59.970328 seconds)
matrix-reminder-bot    | 2020-08-15 12:22:26,030 | apscheduler.executors.default [INFO] Running job "Reminder._fire (trigger: interval[0:01:00], next run at: 2020-08-15 14:23:26 CEST)" (scheduled at 2020-08-15 14:22:26+02:00)
matrix-reminder-bot    | 2020-08-15 12:22:26,030 | matrix_reminder_bot.reminder [DEBUG] Reminder in room !mybotroom:myhomeserver.tld fired: test explicit alarms
matrix-reminder-bot    | 2020-08-15 12:22:26,030 | apscheduler.scheduler [INFO] Added job "Reminder._fire_alarm" to job store "default"
matrix-reminder-bot    | 2020-08-15 12:22:26,033 | apscheduler.scheduler [DEBUG] Looking for jobs to run
matrix-reminder-bot    | 2020-08-15 12:22:26,033 | apscheduler.scheduler [DEBUG] Next wakeup is due at 2020-08-15 14:23:26+02:00 (in 59.966343 seconds)
matrix-reminder-bot    | 2020-08-15 12:22:26,274 | apscheduler.executors.default [INFO] Job "Reminder._fire (trigger: interval[0:01:00], next run at: 2020-08-15 14:23:26 CEST)" executed successfully
matrix-reminder-bot    | 2020-08-15 12:23:26,032 | apscheduler.scheduler [DEBUG] Looking for jobs to run
matrix-reminder-bot    | 2020-08-15 12:23:26,032 | apscheduler.scheduler [DEBUG] Next wakeup is due at 2020-08-15 14:24:26+02:00 (in 59.967652 seconds)
```
We are now at the same point as with the implicit delta before, except we find something:
```
matrix-reminder-bot    | 2020-08-15 12:23:26,033 | apscheduler.executors.default [INFO] Running job "Reminder._fire (trigger: interval[0:01:00], next run at: 2020-08-15 14:24:26 CEST)" (scheduled at 2020-08-15 14:23:26+02:00)
matrix-reminder-bot    | 2020-08-15 12:23:26,033 | matrix_reminder_bot.reminder [DEBUG] Reminder in room !mybotroom:myhomeserver.tld fired: test explicit alarms
```
Ok weird, this again sent the warning "alarm $alarmtext will go off in 5m". It should instead post "Alarm: $alarmtext". Further it says delta=5m, when it should be (and was) our explicit 1m.
```
matrix-reminder-bot    | 2020-08-15 12:23:26,033 | apscheduler.scheduler [INFO] Added job "Reminder._fire_alarm" to job store "default"
matrix-reminder-bot    | 2020-08-15 12:23:26,036 | apscheduler.scheduler [DEBUG] Looking for jobs to run
matrix-reminder-bot    | 2020-08-15 12:23:26,036 | apscheduler.scheduler [DEBUG] Next wakeup is due at 2020-08-15 14:24:26+02:00 (in 59.963353 seconds)
matrix-reminder-bot    | 2020-08-15 12:23:26,289 | apscheduler.executors.default [INFO] Job "Reminder._fire (trigger: interval[0:01:00], next run at: 2020-08-15 14:24:26 CEST)" executed successfully
matrix-reminder-bot    | 2020-08-15 12:24:26,029 | apscheduler.scheduler [DEBUG] Looking for jobs to run
matrix-reminder-bot    | 2020-08-15 12:24:26,029 | apscheduler.scheduler [DEBUG] Next wakeup is due at 2020-08-15 14:25:26+02:00 (in 59.970623 seconds)
```
And repeat.
```
matrix-reminder-bot    | 2020-08-15 12:24:26,029 | apscheduler.executors.default [INFO] Running job "Reminder._fire (trigger: interval[0:01:00], next run at: 2020-08-15 14:25:26 CEST)" (scheduled at 2020-08-15 14:24:26+02:00)
matrix-reminder-bot    | 2020-08-15 12:24:26,030 | matrix_reminder_bot.reminder [DEBUG] Reminder in room !mybotroom:myhomeserver.tld fired: test explicit alarms
matrix-reminder-bot    | 2020-08-15 12:24:26,030 | apscheduler.scheduler [INFO] Added job "Reminder._fire_alarm" to job store "default"
matrix-reminder-bot    | 2020-08-15 12:24:26,033 | apscheduler.scheduler [DEBUG] Looking for jobs to run
matrix-reminder-bot    | 2020-08-15 12:24:26,034 | apscheduler.scheduler [DEBUG] Next wakeup is due at 2020-08-15 14:25:26+02:00 (in 59.965966 seconds)
matrix-reminder-bot    | 2020-08-15 12:24:26,299 | apscheduler.executors.default [INFO] Job "Reminder._fire (trigger: interval[0:01:00], next run at: 2020-08-15 14:25:26 CEST)" executed successfully
```
Okay, it kinda works. I cancel the reminder, this should be the end of it:
```
matrix-reminder-bot    | 2020-08-15 12:24:38,099 | matrix_reminder_bot.callbacks [DEBUG] Command received: !cancelreminder test explicit alarms
matrix-reminder-bot    | 2020-08-15 12:24:38,099 | matrix_reminder_bot.bot_commands [DEBUG] Known reminders: {('!mybotroom:myhomeserver.tld', 'TEST EXPLICIT ALARMS'): <matrix_reminder_bot.reminder.Reminder object at 0x7f878851a340>}
matrix-reminder-bot    | 2020-08-15 12:24:38,099 | matrix_reminder_bot.bot_commands [DEBUG] Deleting reminder in room !mybotroom:myhomeserver.tld: test explicit alarms
matrix-reminder-bot    | 2020-08-15 12:24:38,099 | matrix_reminder_bot.reminder [DEBUG] Cancelling reminder in room !mybotroom:myhomeserver.tld: test explicit alarms
matrix-reminder-bot    | 2020-08-15 12:24:38,102 | apscheduler.scheduler [INFO] Removed job d2f810f9a5de46c0bd892e528498948c
matrix-reminder-bot    | 2020-08-15 12:24:38,102 | apscheduler.scheduler [INFO] Removed job a69969324f9941a88436321abe736c98
matrix-reminder-bot    | 2020-08-15 12:25:26,018 | apscheduler.scheduler [DEBUG] Looking for jobs to run
matrix-reminder-bot    | 2020-08-15 12:25:26,018 | apscheduler.scheduler [DEBUG] Next wakeup is due at 2020-08-15 14:27:26.03060
```
That was an empty alarm-wakeup.
```
matrix-reminder-bot    | 2020-08-15 12:27:26,049 | apscheduler.scheduler [DEBUG] Looking for jobs to run
matrix-reminder-bot    | 2020-08-15 12:27:26,049 | apscheduler.scheduler [DEBUG] Next wakeup is due at 2020-08-15 14:28:26.033388+02:00 (in 59.983930 seconds)
```
It schedules a 1m interval, but also thinks the next alarm is in 5m:
```
matrix-reminder-bot    | 2020-08-15 12:27:26,050 | apscheduler.executors.default [INFO] Running job "Reminder._fire_alarm (trigger: interval[0:05:00], next run at: 2020-08-15 12:32:26 UTC)" (scheduled at 2020-08-15 12:27:26.030608+00:00)
matrix-reminder-bot    | 2020-08-15 12:27:26,050 | matrix_reminder_bot.reminder [DEBUG] Alarm in room !mybotroom:myhomeserver.tld fired: test explicit alarms
matrix-reminder-bot    | 2020-08-15 12:27:26,333 | apscheduler.executors.default [INFO] Job "Reminder._fire_alarm (trigger: interval[0:05:00], next run at: 2020-08-15 12:32:26 UTC)" executed successfully
```
Also, this time we got the "Alarm: $alarmtext"!  And at this point I don't even know anymore. I'm getting the same alarm in an interval of first 1m, then another 4m, repeat.
```
matrix-reminder-bot    | 2020-08-15 12:27:52,923 | matrix_reminder_bot.callbacks [DEBUG] Command received: !listreminders
matrix-reminder-bot    | 2020-08-15 12:28:26,037 | apscheduler.scheduler [DEBUG] Looking for jobs to run
matrix-reminder-bot    | 2020-08-15 12:28:26,037 | apscheduler.scheduler [DEBUG] Next wakeup is due at 2020-08-15 14:32:26.030608+02:00 (in 239.993096 seconds)
matrix-reminder-bot    | 2020-08-15 12:28:26,038 | apscheduler.executors.default [INFO] Running job "Reminder._fire_alarm (trigger: interval[0:05:00], next run at: 2020-08-15 12:33:26 UTC)" (scheduled at 2020-08-15 12:28:26.033388+00:00)
matrix-reminder-bot    | 2020-08-15 12:28:26,038 | matrix_reminder_bot.reminder [DEBUG] Alarm in room !mybotroom:myhomeserver.tld fired: test explicit alarms
matrix-reminder-bot    | 2020-08-15 12:28:27,762 | apscheduler.executors.default [INFO] Job "Reminder._fire_alarm (trigger: interval[0:05:00], next run at: 2020-08-15 12:33:26 UTC)" executed successfully
matrix-reminder-bot    | 2020-08-15 12:32:26,037 | apscheduler.scheduler [DEBUG] Looking for jobs to run
matrix-reminder-bot    | 2020-08-15 12:32:26,037 | apscheduler.scheduler [DEBUG] Next wakeup is due at 2020-08-15 14:33:26.033388+02:00 (in 59.995864 seconds)
matrix-reminder-bot    | 2020-08-15 12:32:26,038 | apscheduler.executors.default [INFO] Running job "Reminder._fire_alarm (trigger: interval[0:05:00], next run at: 2020-08-15 12:37:26 UTC)" (scheduled at 2020-08-15 12:32:26.030608+00:00)
matrix-reminder-bot    | 2020-08-15 12:32:26,038 | matrix_reminder_bot.reminder [DEBUG] Alarm in room !mybotroom:myhomeserver.tld fired: test explicit alarms
matrix-reminder-bot    | 2020-08-15 12:32:26,280 | apscheduler.executors.default [INFO] Job "Reminder._fire_alarm (trigger: interval[0:05:00], next run at: 2020-08-15 12:37:26 UTC)" executed successfully
matrix-reminder-bot    | 2020-08-15 12:33:26,045 | apscheduler.scheduler [DEBUG] Looking for jobs to run
matrix-reminder-bot    | 2020-08-15 12:33:26,045 | apscheduler.scheduler [DEBUG] Next wakeup is due at 2020-08-15 14:37:26.030608+02:00 (in 239.985421 seconds)
matrix-reminder-bot    | 2020-08-15 12:33:26,045 | apscheduler.executors.default [INFO] Running job "Reminder._fire_alarm (trigger: interval[0:05:00], next run at: 2020-08-15 12:38:26 UTC)" (scheduled at 2020-08-15 12:33:26.033388+00:00)
matrix-reminder-bot    | 2020-08-15 12:33:26,046 | matrix_reminder_bot.reminder [DEBUG] Alarm in room !mybotroom:myhomeserver.tld fired: test explicit alarms
matrix-reminder-bot    | 2020-08-15 12:33:26,545 | apscheduler.executors.default [INFO] Job "Reminder._fire_alarm (trigger: interval[0:05:00], next run at: 2020-08-15 12:38:26 UTC)" executed successfully
```

At this point I try `!silence`. Bot answers (not reflected in the log)

> Unknown alarm or reminder ''.

The 1m+4m alarms continue...

Amendment:
Looks like recurring != modified alarm interval, which explains the 1m+4m. I reckon I only cancelled the one out of 3, thus 2 continue going off.

Also I did `!silence test explicit alarms` which would be the correct command, but

> Unknown alarm or reminder 'test explicit alarms'.

**Comment by anoadragon453** [comment] 2020-08-24 17:29
I've done some fixes to alarms and `!silence` in https://github.com/anoadragon453/matrix-reminder-bot/commit/6626e93c4c410cde28da7cc00d9c401f58e93244. Could you see if this clears up your problems?

**Comment by HarHarLinks** [comment] 2020-09-14 12:02
- [x] `!cancelreminder` now seems to catch all associated ongoing alarms
- [x] `!silence` w/o args does automatically match a single ongoing alarm.
- [ ] `!silence` 2/o args in case of 2 ongoing chooses only the first instead of asking for clarification or match all (although at least the action is echoed to the user correctly). Second alarm continues until another `!silence`
- i miss something?

**Comment by anoadragon453** [comment] 2020-09-14 14:56
> Second alarm continues until another `!silence`. This is judging for your commit msg by design, tho I don't see the reasoning?

Yes this was by design initially, though thinking about it now I can see two possible actions a user might want to take in a situation where 2 alarms are going off concurrently:

1. The user wants to silence one alarm
1. The user wants to silence all alarms

Currently, to do `1.` the user could use either `!silence alarm_name` or `!silence. In the latter case, the user wouldn't exactly know which alarm they were silencing though, which is confusing.

To do `2.`, the user needs to do `!silence <alarm_name_1>` and `!silence <alarm_name_2>`.

I believe you're right in instead having `!silence` just silence all firing alarms in the room. With this change, the situation becomes such that to do `1.` the user would use `!silence alarm_name`, and to do `2.` the user would just do `!silence`. Much simpler and only requires a single command in both cases.

I've created an issue for this specific problem here:

**Comment by anoadragon453** [comment] 2020-09-14 14:57
> i miss something?

Hopefully not? :D If the above issue is the last remaining one then closing this issue would be ideal :slightly_smiling_face:

**Comment by HarHarLinks** [comment] 2020-09-14 15:06
I think that is the most sensible solution. The only other justifiable alternative I see would be to make naked `!silence` respond to the alarm that (re)triggered most recently.

**Comment by anoadragon453** [comment] 2020-09-14 15:11
Could do that, but what if another alarm fires just before you hit send? :P

**Comment by HarHarLinks** [comment] 2020-09-14 16:08
I totally think #47 is the better way, just wanted to mention it.

**Comment by HarHarLinks** [comment] 2020-12-24 15:46
closing since #47 covers the remaining issues

**Closed** 2020-12-24 15:45 UTC
